stages:
    - triggers

# Trigger development pipeline when creating a mergerequest
trigger_DevPipeline:
   stage: triggers
   trigger:
       include:             
           - local: CSV-Com/Pipelines/DevPipeline.yml
   only: 
       - merge_requests
       - web

# Trigger feature pipeline when pushing to feature branch
trigger_FeaturePipeline:    
    stage: triggers
    trigger:
        include: CSV-Com/Pipelines/FeaturePipeline.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "web"
        when: never
      - if: $CI_COMMIT_BRANCH =~ /^Feature[0-9]*_*//i
#    only:
#      - /^Feature[0-9]*_*//i # See naming conventions for features https://sbict.atlassian.net/wiki/spaces/CVS/pages/7241742/GIT-Flow#Naamgeving

# Trigger release pipeline when pushing to release branch
trigger_ReleasePipeline:
   stage: triggers
   trigger:
       include: ReleasePipeline.yml
   only:
      - /^Release[0-9]*_*//i # See naming conventions for features https://sbict.atlassian.net/wiki/spaces/CVS/pages/7241742/GIT-Flow#Naamgeving
