workflow:
  rules:
    - when: always

variables:  
  DOTNET_IMAGE: "mcr.microsoft.com/dotnet/sdk:7.0" # Default image   for gitlabrunner
  DOCKER_IMAGE: "docker:stable"
  NODE_IMAGE: "node:18"  
  SOLUTION_FOLDER: "CSV-Com"
  SOLUTION: "$SOLUTION_FOLDER/CSV-Com.sln"
  NODE_FOLDER: "webapp"
  BUILD_CONFIGURATION: "Debug"
  DOTNET_DOCKER_IMAGE_NAME: "$CI_REGISTRY/client-volgsysteem/cvs-com/api"
  NODE_DOCKER_IMAGE_NAME: "$CI_REGISTRY/client-volgsysteem/cvs-com/webapp"
  DOTNET_DOCKER_IMAGE_FILENAME: "dotnet_docker_image"
  NODE_DOCKER_IMAGE_FILENAME: "node_docker_image"

stages: 
  - image-build    
  - image-publish
  - build
  - test

dotnet-build:
  before_script:
  - shopt -s globstar # setting for enabling wildcards in bash **/*.csproj
  - 'dotnet restore $SOLUTION' # dotnet build does also restore but an explicit restore is better when using GitLab for caching purposes
  stage: build
  script:
    # Build all .NET projects
    - | 
      for project in **/*.csproj; do
        dotnet build "$project" -c $BUILD_CONFIGURATION --no-restore
      done
  image: $DOTNET_IMAGE
  artifacts:
    paths:
      - '**/bin'

dotnet-test:
  stage: test
  script:
    - dotnet test $SOLUTION -c $BUILD_CONFIGURATION --collect:"XPlat Code Coverage" --logger "junit;LogFileName=TestResults.xml" # Run and publish testresults with junit to gitlab
  image: $DOTNET_IMAGE
  artifacts:
    paths:
      - '**/TestResults.xml'
      - '**/coverage.cobertura.xml'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: '**/coverage.cobertura.xml'
      junit: 
        - '**/TestResults.xml'
    when: always  # Keep result files. Even when tests fail.
  dependencies:
    - dotnet-build
    
image-build-job:
  services:
  - name: docker:20.10.16-dind
  # before_script:
  # - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  stage: image-build
  script:
    # Dotnet build  
    - cd CSV-Com
    - docker build -t $DOTNET_DOCKER_IMAGE_NAME -f "./API/Dockerfile" "."
    - cd ..
    - mkdir image
    - docker save $DOTNET_DOCKER_IMAGE_NAME > image/${DOTNET_DOCKER_IMAGE_FILENAME}.tar
    # Node build
    - cd CSV-Com/webapp
    - docker build -t $NODE_DOCKER_IMAGE_NAME -f "./Dockerfile" "."
    - cd ../..
    - docker save $NODE_DOCKER_IMAGE_NAME > image/${NODE_DOCKER_IMAGE_FILENAME}.tar
    # - docker push $DOTNET_DOCKER_IMAGE_NAME
  image: $DOCKER_IMAGE
  artifacts:
    paths:
      - image

image-publish-job:
  services:
  - name: docker:20.10.16-dind
    command:
      [
        '--insecure-registry=docker-registry.sbict.local',
        '--insecure-registry=registry.sbict.local',
        '--insecure-registry=gitlab.sbict.local'
      ]
  before_script:
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  stage: image-publish
  script:
    - docker load -i image/${DOTNET_DOCKER_IMAGE_FILENAME}.tar
    - docker load -i image/${NODE_DOCKER_IMAGE_FILENAME}.tar
    - docker push $DOTNET_DOCKER_IMAGE_NAME
    - docker push $NODE_DOCKER_IMAGE_NAME
  image: $DOCKER_IMAGE

node-build:
  before_script:
  - cd $SOLUTION_FOLDER/$NODE_FOLDER
  - npm install
  - export CI=false
  stage: build
  script:
  - yarn build
  image: $NODE_IMAGE
  artifacts:
    paths:
      - '$SOLUTION_FOLDER/$NODE_FOLDER/build/'

node-test:
  before_script:
    - cd $SOLUTION_FOLDER/$NODE_FOLDER
    - npm install
  stage: test
  script:
    - npx nyc --reporter=cobertura npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths: # NOTE: Is it even necessary to artifact these files if their already being used in the reports? Keep this until we are sure that codecoverage is working
      - '**/junit.xml'
      - '**/coverage/'
      - '**/coverage-final.json'
    when: always
    reports:
      junit:
        - '**/junit.xml'
      coverage_report:
        coverage_format: cobertura
        path: '**/coverage-final.json'
  image: $NODE_IMAGE
  dependencies:
    - node-build