workflow:
  rules:
    - when: always

stages:
    - test
    - build

feature_build-job:
  stage: build
  needs: [feature_test-job]
  script:
    - echo "Build feature pipeline"

feature_test-job:
  stage: test
  script:
    - echo "Test feature pipeline"
