//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.CoachingPrograms.Queries.GetCoachingProgram.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetCoachingProgramDto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetCoachingProgramDto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.CoachingPrograms.Queries.GetCoachingProgram.Resources.GetCoachingProg" +
                            "ramDto", typeof(GetCoachingProgramDto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercieel jobcoach traject.
        /// </summary>
        internal static string CommercialCoachingProgram {
            get {
                return ResourceManager.GetString("CommercialCoachingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe jobcoach.
        /// </summary>
        internal static string ExternJobCoach {
            get {
                return ResourceManager.GetString("ExternJobCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interne jobcoach.
        /// </summary>
        internal static string InternJobCoach {
            get {
                return ResourceManager.GetString("InternJobCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonsgebonden budget (pgb).
        /// </summary>
        internal static string PGB {
            get {
                return ResourceManager.GetString("PGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prive jobcoach traject.
        /// </summary>
        internal static string PrivateCoachingProgram {
            get {
                return ResourceManager.GetString("PrivateCoachingProgram", resourceCulture);
            }
        }
    }
}
