//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddressValidationRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressValidationRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Rules.Resources.AddressValidationRules", typeof(AddressValidationRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer toevoeging mag niet langer zijn dan {0} karakters..
        /// </summary>
        internal static string HousenumberAddtionMaxLength {
            get {
                return ResourceManager.GetString("HousenumberAddtionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer mag niet groter zijn dan {0}..
        /// </summary>
        internal static string HouseNumberMaxValue {
            get {
                return ResourceManager.GetString("HouseNumberMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer kan geen negatieve waarde bevatten..
        /// </summary>
        internal static string HouseNumberNotNegativeValue {
            get {
                return ResourceManager.GetString("HouseNumberNotNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer is verplicht..
        /// </summary>
        internal static string HouseNumberRequired {
            get {
                return ResourceManager.GetString("HouseNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode &apos;{0}&apos; is geen geldige postcode..
        /// </summary>
        internal static string PostalCodeInvalid {
            get {
                return ResourceManager.GetString("PostalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode mag niet langer zijn dn {0} karakters..
        /// </summary>
        internal static string PostalCodeMaxLength {
            get {
                return ResourceManager.GetString("PostalCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode is verplicht..
        /// </summary>
        internal static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woonplaats mag niet langer zijn dan {0} karakters..
        /// </summary>
        internal static string ResidenceMaxLength {
            get {
                return ResourceManager.GetString("ResidenceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woonplaats is verplicht..
        /// </summary>
        internal static string ResidenceRequired {
            get {
                return ResourceManager.GetString("ResidenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straatnaam mag niet langer zijn dan  {0} karakters..
        /// </summary>
        internal static string StreetNameMaxLength {
            get {
                return ResourceManager.GetString("StreetNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straatnaam is verplicht..
        /// </summary>
        internal static string StreetNameRequired {
            get {
                return ResourceManager.GetString("StreetNameRequired", resourceCulture);
            }
        }
    }
}
