//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoachingProgramValidationRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoachingProgramValidationRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Rules.Resources.CoachingProgramValidationRules", typeof(CoachingProgramValidationRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het budget mag geen negatieve waarde bevatten..
        /// </summary>
        internal static string BudgetAmmountPositive {
            get {
                return ResourceManager.GetString("BudgetAmmountPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliënt met id &apos;{0}&apos; bestaat niet..
        /// </summary>
        internal static string ClientDoesNotExists {
            get {
                return ResourceManager.GetString("ClientDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliënt is verplicht..
        /// </summary>
        internal static string ClientRequired {
            get {
                return ResourceManager.GetString("ClientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traject met id &apos;{0}&apos; bestaat niet..
        /// </summary>
        internal static string CoachingProgramDoesNotExists {
            get {
                return ResourceManager.GetString("CoachingProgramDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traject type heeft geen geldige waarde..
        /// </summary>
        internal static string CoachingProgramTypeInValid {
            get {
                return ResourceManager.GetString("CoachingProgramTypeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De van datum kan niet na de tot datum liggen..
        /// </summary>
        internal static string FromDateAfterUntilDate {
            get {
                return ResourceManager.GetString("FromDateAfterUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De van datum is verplicht..
        /// </summary>
        internal static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het uurtarief mag geen negatieve waarde bevatten..
        /// </summary>
        internal static string HourlyRatePositive {
            get {
                return ResourceManager.GetString("HourlyRatePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uurtarief is verplicht..
        /// </summary>
        internal static string HourlyRateRequired {
            get {
                return ResourceManager.GetString("HourlyRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordernummer mag niet langer zijn dan {0} karakters..
        /// </summary>
        internal static string OrderNumberMaxLength {
            get {
                return ResourceManager.GetString("OrderNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatie met id &apos;{0}&apos; bestaat niet..
        /// </summary>
        internal static string OrganizationDoesNotExists {
            get {
                return ResourceManager.GetString("OrganizationDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel mag niet langer zijn dan {0} karakters..
        /// </summary>
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel is verplicht..
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tot datum kan niet voor de van datum liggen..
        /// </summary>
        internal static string UntilDateBeforeFromDate {
            get {
                return ResourceManager.GetString("UntilDateBeforeFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tot datum is verplicht..
        /// </summary>
        internal static string UntilDateRequired {
            get {
                return ResourceManager.GetString("UntilDateRequired", resourceCulture);
            }
        }
    }
}
