//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkingContractValidationRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkingContractValidationRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Rules.Resources.WorkingContractValidationRules", typeof(WorkingContractValidationRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract heeft een ongeldige waarde..
        /// </summary>
        internal static string ContractInvalidValue {
            get {
                return ResourceManager.GetString("ContractInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De van datum kan niet na de tot datum liggen..
        /// </summary>
        internal static string FromDateAfterUntilDate {
            get {
                return ResourceManager.GetString("FromDateAfterUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De van datum kan niet in de toekomst liggen..
        /// </summary>
        internal static string FromDateInFuture {
            get {
                return ResourceManager.GetString("FromDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functie mag niet langer zijn dan {0} karakters..
        /// </summary>
        internal static string FunctionMaxCharacters {
            get {
                return ResourceManager.GetString("FunctionMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functie is verplicht..
        /// </summary>
        internal static string FunctionRequired {
            get {
                return ResourceManager.GetString("FunctionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatie is verplicht..
        /// </summary>
        internal static string OrganizationRequired {
            get {
                return ResourceManager.GetString("OrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tot datum kan niet in de toekomst liggen..
        /// </summary>
        internal static string ToDateInFuture {
            get {
                return ResourceManager.GetString("ToDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tot datum kan niet voor de van datum liggen..
        /// </summary>
        internal static string UntilDateBeforeFromDate {
            get {
                return ResourceManager.GetString("UntilDateBeforeFromDate", resourceCulture);
            }
        }
    }
}
