// <auto-generated />
using Infrastructure.Persistence.CVS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.CVS.Migrations
{
    [DbContext(typeof(CVSDbContext))]
    partial class CVSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.CVS.Domain.Cliënt", b =>
                {
                    b.Property<int>("CliëntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BSNNummer")
                        .HasColumnType("int");

                    b.Property<string>("Emailadres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int");

                    b.Property<string>("HuisnummerToevoeging")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobielnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Roepnaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StraatNaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tussenvoegsel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voorletters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CliëntId");

                    b.ToTable("Cliënten");
                });

            modelBuilder.Entity("Domain.CVS.Domain.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });
#pragma warning restore 612, 618
        }
    }
}
